"""Include OwnerSession table.

Revision ID: f929ed5ed4f4
Revises: 5237443a9ba0
Create Date: 2024-02-10 15:24:04.906129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f929ed5ed4f4'
down_revision: Union[str, None] = '5237443a9ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_sessions',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.alter_column('owners', 'email',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('owners', 'password',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('owners', 'password',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('owners', 'email',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_table('owner_sessions')
    # ### end Alembic commands ###
