"""Module defining OwnerSessionModel class."""

from uuid import UUID, uuid1

from sqlalchemy import ForeignKey
from sqlalchemy.orm import Mapped, mapped_column

from src.main.database.base import Base


class OwnerSessionModel(Base):
    """Model representing owner sessions in the database.

    Parameters
    ----------
    Base : sqlalchemy.ext.declarative.api.Base
        The base class for declarative class definitions.

    Attributes
    ----------
    __tablename__ : str
        The name of the table in the database.
    session_id : sqlalchemy.orm.Mapped[uuid.UUID]
        The UUID of the session. Defaults to a new UUID generated by uuid1().
    owner_id : sqlalchemy.orm.Mapped[uuid.UUID]
        The UUID of the owner associated with this session.

    Notes
    -----
    This model defines the structure of the 'owner_sessions' table in the
    database. Each session is associated with a specific owner.
    """

    __tablename__ = "owner_sessions"

    session_id: Mapped[UUID] = mapped_column(
        primary_key=True,
        default=uuid1,
    )
    owner_id: Mapped[UUID] = mapped_column(
        ForeignKey("owners.id"),
        nullable=False,
    )
